//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarrierCards.Website.ListingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/WarrierCards.Service.DataObjects")]
    [System.SerializableAttribute()]
    public partial class SearchCriteria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> CardColorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WarrierCards.Website.ListingService.CardTypes CardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal HighPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemsReturnedPerRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LastItemIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LowPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> CardColors {
            get {
                return this.CardColorsField;
            }
            set {
                if ((object.ReferenceEquals(this.CardColorsField, value) != true)) {
                    this.CardColorsField = value;
                    this.RaisePropertyChanged("CardColors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WarrierCards.Website.ListingService.CardTypes CardType {
            get {
                return this.CardTypeField;
            }
            set {
                if ((this.CardTypeField.Equals(value) != true)) {
                    this.CardTypeField = value;
                    this.RaisePropertyChanged("CardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal HighPrice {
            get {
                return this.HighPriceField;
            }
            set {
                if ((this.HighPriceField.Equals(value) != true)) {
                    this.HighPriceField = value;
                    this.RaisePropertyChanged("HighPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemsReturnedPerRequest {
            get {
                return this.ItemsReturnedPerRequestField;
            }
            set {
                if ((this.ItemsReturnedPerRequestField.Equals(value) != true)) {
                    this.ItemsReturnedPerRequestField = value;
                    this.RaisePropertyChanged("ItemsReturnedPerRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastItemIndex {
            get {
                return this.LastItemIndexField;
            }
            set {
                if ((this.LastItemIndexField.Equals(value) != true)) {
                    this.LastItemIndexField = value;
                    this.RaisePropertyChanged("LastItemIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LowPrice {
            get {
                return this.LowPriceField;
            }
            set {
                if ((this.LowPriceField.Equals(value) != true)) {
                    this.LowPriceField = value;
                    this.RaisePropertyChanged("LowPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardTypes", Namespace="http://schemas.datacontract.org/2004/07/WarrierCards.Service.DataObjects.Common")]
    public enum CardTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HinduWeddingCard = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChristianWeddingCard = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MuslimWeddingCard = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralInvitationCard = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardItem", Namespace="http://schemas.datacontract.org/2004/07/WarrierCards.Service.DataObjects")]
    [System.SerializableAttribute()]
    public partial class CardItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardMainImagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardModelNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CardOrginalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CardSellingPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPortraitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardId {
            get {
                return this.CardIdField;
            }
            set {
                if ((this.CardIdField.Equals(value) != true)) {
                    this.CardIdField = value;
                    this.RaisePropertyChanged("CardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardMainImagePath {
            get {
                return this.CardMainImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.CardMainImagePathField, value) != true)) {
                    this.CardMainImagePathField = value;
                    this.RaisePropertyChanged("CardMainImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardModelNumber {
            get {
                return this.CardModelNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardModelNumberField, value) != true)) {
                    this.CardModelNumberField = value;
                    this.RaisePropertyChanged("CardModelNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardName {
            get {
                return this.CardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNameField, value) != true)) {
                    this.CardNameField = value;
                    this.RaisePropertyChanged("CardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CardOrginalPrice {
            get {
                return this.CardOrginalPriceField;
            }
            set {
                if ((this.CardOrginalPriceField.Equals(value) != true)) {
                    this.CardOrginalPriceField = value;
                    this.RaisePropertyChanged("CardOrginalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CardSellingPrice {
            get {
                return this.CardSellingPriceField;
            }
            set {
                if ((this.CardSellingPriceField.Equals(value) != true)) {
                    this.CardSellingPriceField = value;
                    this.RaisePropertyChanged("CardSellingPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPortrait {
            get {
                return this.IsPortraitField;
            }
            set {
                if ((this.IsPortraitField.Equals(value) != true)) {
                    this.IsPortraitField = value;
                    this.RaisePropertyChanged("IsPortrait");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ListingService.IListingService")]
    public interface IListingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/GetCardsList", ReplyAction="http://tempuri.org/IListingService/GetCardsListResponse")]
        System.Collections.Generic.List<WarrierCards.Website.ListingService.CardItem> GetCardsList(WarrierCards.Website.ListingService.SearchCriteria searchCriteria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListingServiceChannel : WarrierCards.Website.ListingService.IListingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListingServiceClient : System.ServiceModel.ClientBase<WarrierCards.Website.ListingService.IListingService>, WarrierCards.Website.ListingService.IListingService {
        
        public ListingServiceClient() {
        }
        
        public ListingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WarrierCards.Website.ListingService.CardItem> GetCardsList(WarrierCards.Website.ListingService.SearchCriteria searchCriteria) {
            return base.Channel.GetCardsList(searchCriteria);
        }
    }
}
